site_name: DAES Project Documentation
repo_url: https://github.com/eo-agh/daes-project-2425-alt

theme:
  name: material

nav:
  - Home: index.md
  - Tutorials:
      - Dask: dask.ipynb
      - STAC: stac.ipynb
      - GeoParquet: geoparquet.ipynb
  - My Project:
      - Description: my_project/desc.md
      - Logbook: my_project/log.md
  - Projects:
      - Ambulances: projects/ambulances.md
      - Anomalies (Sentinel-2): projects/anomalies_sentinel2.md
      - InSAR: projects/insar.md
      - LULC: projects/lulc.md
      - Meteo Data: projects/meteo_data_for_cities.md
      - Surface Reflectance: projects/sr.md
      - Other: projects/other.md
      - Ways of Working: projects/ways_of_working.md

docs_dir: docs
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search
  - mkdocs-jupyter  # Only if you're using notebooks directly
